### ISSUE TITLE
Root element doesn't need to be listed twice.

### ISSUE THREAD

**Issue by tsdubose** [RUC-web/unit-1-project-clarajean#1]
https://github.com/RUC-web/unit-1-project-clarajean/blob/2f47c24ac5402ff511c6c4166b0d5898a01c3cc4/main.css#L5

All the properties for a selector should go inside a single selector.

**Comment by clarajean** [comment]
:root{
  font-family:-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen-Sans, Ubuntu, Cantarell, "Helvetica Neue", sans-serif;
  font-size: 1.1em;
  line-height: 1.65;
}
